# Install Docker compose version 1.29 or Greater
# https://docs.docker.com/compose/install/
# For non-root user follow these additional steps
#   sudo usermod -aG docker $USER                  
#   sudo chgrp docker /usr/local/bin/docker-compose     
#   sudo chmod 750 /usr/local/bin/docker-compose

# TO START: docker-compose -f docker-compose.yaml up -d
# TO START WITH ALERT MANAGER: docker-compose --profile notifications -f docker-compose.yaml up -d
# TO STOP: docker-compose -f docker-compose.yaml down
version: '3.9'
services:
    navigator_nginx:
        image: tailwindsai/navigator_nginx:beta-v3.2.2
        hostname: navigator_nginx
        container_name: navigator_nginx
        depends_on:
            - navigator_cache
            - navigator_db
            - navigator_server
        restart: always
        network_mode: host
        volumes:
            - /etc/localtime:/etc/localtime:ro

    navigator_server:
        image: tailwindsai/navigator_manager:beta-v3.2.2
        hostname: navigator_server
        container_name: navigator_server
        restart: always
        environment:
            - AM_URL=http://localhost:9093/api/v1/alerts
            # - PROMETHEUS_ENDPOINT=52.167.189.143
            - AKS_VERSION=1.21.7
            - SCANNERS=ON
            - PROVIDER_SYNC=ON
        depends_on:
            - navigator_cache
            - navigator_db
            - navigator_worker
        network_mode: host
        volumes:
            - $HOME/.config:/root/.config
            - $HOME/.kube:/root/.kube
            - $HOME/.aws:/root/.aws
            - $HOME/.azure:/root/.azure
        command: ["/home/tailwinds/start-server.sh"]

    navigator_worker:
        image: tailwindsai/navigator_manager:beta-v3.2.2
        hostname: navigator_worker
        container_name: navigator_worker
        restart: always
        depends_on:
            - navigator_cache
            - navigator_db
        network_mode: host
        volumes:
            - $HOME/.config:/root/.config
            - $HOME/.kube:/root/.kube
            - $HOME/.aws:/root/.aws
            - $HOME/.azure:/root/.azure
            - $HOME/applications:/root/applications
        command: ["/home/tailwinds/start-worker.sh"]

    navigator_cache:
        image: tailwindsai/navigator_cache:beta-v3.2.2
        hostname: navigator_cache
        container_name: navigator_cache
        restart: always
        network_mode: host
        volumes:
            - navigator_cache_vol:/data
    
    navigator_db:
        image: tailwindsai/navigator_db:beta-v3.2.2
        container_name: navigator_db
        hostname: navigator_db
        restart: always
        network_mode: host
        volumes:
            - navigator_db_vol:/data/db
            - navigator_db_vol:/data/configdb

    navigator_notifications:
        image: tailwindsai/navigator_notifications:beta-v3.2.2
        profiles: ["notifications"]
        restart: always
        command:
            - '--config.file=/etc/alertmanager/config.yaml'
            - '--storage.path=/alertmanager'
        network_mode: host
        volumes:
            - $HOME/.config/alertmanager:/etc/alertmanager

volumes:
    navigator_db_vol:
        driver: local
    navigator_cache_vol:
        driver: local
