---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: tailwinds-cr
rules:
- apiGroups: [""]
  resources: ["pods", "endpoints"]
  verbs: ["get", "watch", "list"]
---
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tailwinds-crb
subjects:
- kind: ServiceAccount
  name: tailwinds-sa
  namespace: tailwinds
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: tailwinds-cr
  apiGroup: ""
---
apiVersion: v1
kind: Namespace
metadata:
  name: tailwinds
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tailwinds-sa
  namespace: tailwinds
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MSI6eyJ1c2VybmFtZSI6InRhaWx3aW5kc2FpIiwicGFzc3dvcmQiOiJBbmJoa2FAMjAyMCIsImF1dGgiOiJkR0ZwYkhkcGJtUnpZV2s2UVc1aWFHdGhRREl3TWpBPSJ9fX0=
kind: Secret
metadata:
  creationTimestamp: null
  name: regcred
type: kubernetes.io/dockerconfigjson
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dns-diagnostic-server-deployment
  namespace: tailwinds
  labels:
    name: tailwinds-dns
spec:
  replicas: 1
  selector:
    matchLabels:
      name: tailwinds-dns
  template:
    metadata:
      labels:
        name: tailwinds-dns
    spec:
      serviceAccountName: tailwinds-sa
      containers:
      - name: tailwinds-dns-diagnostic-server
        image: tailwindsai/tailwinds-dns-diagnostic-server:beta-v0.1
      imagePullSecrets:
      - name: regcred
      dnsPolicy: "Default"
