---
apiVersion: v1
kind: Namespace
metadata:
  name: tailwinds
---
apiVersion: v1
kind:       ServiceAccount
metadata:
  name:      tailwinds-sa
  namespace: tailwinds

---
apiVersion: rbac.authorization.k8s.io/v1
kind:       ClusterRole
metadata:
  name: tailwinds-cr
rules:
- apiGroups: [""]
  resources:
   - configmaps
   - deployments
   - endpoints
   - horizontalpodautoscalers
   - namespaces
   - nodes
   - persistentvolumes
   - persistentvolumeclaims
   - pods
   - secrets
   - serviceaccounts
   - services
   - statefulsets
  verbs: ["get", "watch", "list"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources:
  - clusterroles
  - clusterrolebindings
  - roles
  - rolebindings
  verbs: ["get", "watch", "list"]
- apiGroups: ["metrics.k8s.io"]
  resources:
  - pods
  - nodes
  verbs: ["get", "watch", "list"]

---
# Binds Popeye to this ClusterRole.
apiVersion: rbac.authorization.k8s.io/v1
kind:       ClusterRoleBinding
metadata:
  name: tailwinds-crb
subjects:
- kind:     ServiceAccount
  name:     tailwinds-sa
  namespace: tailwinds
roleRef:
  kind:     ClusterRole
  name:     tailwinds-cr
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MSI6eyJ1c2VybmFtZSI6InRhaWx3aW5kc2FpIiwicGFzc3dvcmQiOiJBbmJoa2FAMjAyMCIsImF1dGgiOiJkR0ZwYkhkcGJtUnpZV2s2UVc1aWFHdGhRREl3TWpBPSJ9fX0=
kind: Secret
metadata:
  creationTimestamp: null
  name: regcred
type: kubernetes.io/dockerconfigjson
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dns-diagnostic-server-deployment
  namespace: tailwinds
  labels:
    name: tailwinds-dns
spec:
  replicas: 1
  selector:
    matchLabels:
      name: tailwinds-dns
  template:
    metadata:
      labels:
        name: tailwinds-dns
    spec:
      serviceAccountName: tailwinds-sa
      containers:
      - name: tailwinds-dns-diagnostic-server
        image: tailwindsai/tailwinds-dns-diagnostic-server:beta-v0.2.1
        imagePullPolicy: IfNotPresent
      imagePullSecrets:
      - name: regcred
      dnsPolicy: "Default"
