apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: tailwinds-trivy
  labels:
    app: tailwinds-trivy
spec:
  selector:
    matchLabels:
      name: tailwinds-trivy
  template:
    metadata:
      labels:
        app: tailwinds-trivy
    spec:
      containers:
        - name: tailwinds-trivy
          image: tailwinds-trivy:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
      restartPolicy: Always